import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Favicon } from "@/components/layout/Icon";
import { AppStateProvider } from "@/components/layout/StateProvider";
import { Suspense } from "react";
import Loading from "@/app/loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
    ],
  },
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <AppStateProvider>
          <div className="absolute z-50 top-5 left-5">
            <Favicon/>
          </div>
          <Suspense fallback={null}>
            {children}
          </Suspense>
        </AppStateProvider>
      </body>
    </html>
  );
}
